### PR TITLE
Tie interrupts to machine clock

### PR DESCRIPTION
**Pull request by albel727**
Can't really test it since I don't have your emulator fixes, but this should produce an interrupt as closely as possible to 16000 ticks, i.e. 8ms emulated time.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
I've just pushed up the fixes, can you rebase your changes?

**Comment by albel727** [comment]
There.

**Comment by albel727** [comment]
Though I should ask if `cpu.int_enable` is changed at runtime, and most importantly, by the emulated code itself? And if yes, what is the behavior with respect to interrupts that came while `cpu.int_enable` was false? Are they gone forever, or are they marked for future execution and triggered as soon as `cpu.int_enable` is back to true? If the latter, is it one interrupt per all missed interrupts?

**Comment by XAMPPRocky** [comment]
Yes the CPU int_enable is toggled with the `EI` and `DI` instructions. Once an interrupt happens it is toggled off. Any interrupts that try to happen while it's disabled are lost forever.

**Pull request merged**
