### PR TITLE
Remove unreachable pattern

### PR DESCRIPTION
**Pull request by JonasOlson**
Remove an instance of `_ => unreachable!()` that the compiler can figure out automatically.
    
The compiler sees that all possible values are enumerated in the pattern matching, and emits a warning if the `_` pattern is used.

### CODE REVIEW

**Comment by JonasOlson** [comment]
I don't understand GitHub. Why does it say "JonasOlson wants to merge 5 commits" despite some of those already being merged?

**Comment by XAMPPRocky** [comment]
@JonasOlson Thank you for your PR! I believe it might be saying that because you're using the same branch for all of these commits? I'd recommend using separate branches for each PR.

**Comment by JonasOlson** [comment]
> I believe it might be saying that because you're using the same branch for all of these commits?

Hmm, it's possible I'm doing it wrong, but I have created a new branch for each PR, and deleted it (both on my computer and on GitHub) afterwards.

**Comment by XAMPPRocky** [comment]
@JonasOlson Make sure you're also updating your master branch that you're starting with, with the changes from remote. I perform squash and merges so so even when the commits are technically the same they now have a different hash and are thus counted as different commits.

**Comment by JonasOlson** [comment]
> @JonasOlson Make sure you're also updating your master branch with the changes from remote, as I perform squash and merges so so even when the commits are technically the same they now have a different hash and are thus counted as different commits.

I think I did that, but I shall make sure next time.

**Pull request merged**
